export const SET_LOADING_PRODUCTS = "SET_LOADING_PRODUCTS"
export const SET_PRODUCTS = "SET_PRODUCTS"

export const SET_CART = "SET_CART"
export const ADD_CART = "ADD_CART"
export const EDIT_CART = "EDIT_CART"
export const DELETE_CART = "DELETE_CART"
export const DELETE_ALL_CART = "DELETE_ALL_CART"

export const SET_HISTORIES = "SET_HISTORIES"
export const SET_LOADING_HISTORIES = "SET_LOADING_HISTORIES"
export const REMOVE_HISTORIES = "REMOVE_HISTORIES"

export const SET_AUTH = "SET_AUTH"